// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://radmtegdwxsfngjpvbaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZG10ZWdkd3hzZm5nanB2YmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjcwNzYsImV4cCI6MjA1ODY0MzA3Nn0.yqpjIsAZ9UuIckRYUcAAqdB3TyWKNgJpiI7FFjYhP9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);